### ISSUE TITLE
Support SSR of collections

### ISSUE THREAD

**Issue by dhmacs** [algolia/shopify-hydrogen-algolia#2]
This template renders the collection only client side. Can you provide an example with server side rendering?

**Comment by qinglinye** [comment]
Hello,
React InstantSearch hooks library is not yet compatible with Shopify Hydrogen SSR.
Our engineering team is currently assessing the possibility of a future compatibility.
Thanks,
Best regards,

**Comment by dhmacs** [comment]
@qinglinye I've been able to make it work by using `getServerState` 👍

**Comment by qinglinye** [comment]
Hi @dhmacs,
Our engineering team has encountered before some problems with the Hydrogen server side module and getServerState.
I think with the new version of our library, the issue gets resolved, I'm also able to use SSR in hydrogen now.
We'll check in our side and update the example.
Thanks a lot!
Best regards,
