### ISSUE TITLE
Algolia-Autocomplete Not Working

### ISSUE THREAD

**Issue by reubence** [algolia/shopify-hydrogen-algolia#3]
The Autocomplete on the Header component does not seem to work as intended i.e. it doesn't suggest any word completions.

None of the files have been modified, except for the `algolia.config.json` file. 

We're looking to implement Algolia on our Hydrogen Storefront, any help is appreciated.

**Comment by reubence** [comment]
It's giving me this error `Index "shopify" does not exist`

**Comment by qinglinye** [comment]
Hello @reubence,
In the algolia.config.json, the prefix should be aligned with our shopify extension and a query sugguestion index should be generated.
For example
  "prefix": "shopify_",
  "QSindex": "shopify_querysuggestions"
Thanks

**Comment by reubence** [comment]
Yeah that helps!
