### ISSUE TITLE
Autocomplete Dropdown Doesn't Close On Click Outside Container

### ISSUE THREAD

**Issue by reubence** [algolia/shopify-hydrogen-algolia#4]
Hey Team, I noticed that the Autocomplete examples provided on Algolia Docs ([for example](https://codesandbox.io/s/github/algolia/autocomplete/tree/next/examples/query-suggestions?file=/app.tsx)) supports the "on click outside" state by default and closes the dropdown when clicked outside.

This doesn't seem to be working with the Hydrogen example in this repo, I'm on a fresh installation of react 18.2 and Node 18.6.0. 

I'm wondering if i's an issue with React 18. Any help is much appreciated!

**Comment by qinglinye** [comment]
Hi, this template render the aa-panel of autocomplete on the hydrogen header to stick it. If you change to a classic flyout I think it will work.
BTW we have checked in a new template.
