### ISSUE TITLE
Hydrogen / Remix

### ISSUE THREAD

**Issue by j-Riv** [algolia/shopify-hydrogen-algolia#6]
Hey Guys, Hydrogen has added Remix, can we get an example on how to get this working with the new demo-store example. Thanks.

**Comment by pranavchavda** [comment]
+1

**Comment by hi-im-si** [comment]
+1

**Comment by TOTALINK** [comment]
Why there is no proper documentation for algolia and hydrogen ! 
what we suppose to do with your demo, its outdated and there is no documentation.

**Comment by TOTALINK** [comment]
i got in touch with them for support and see if they have any documentation and guess what, they offered me a 15 minute session for 45 days later, i switch back to free shopify search app where i have more control and better support, every hydrogen integration i saw have proper documentation already except this company, they think this demo really help!!!!

**Comment by qinglinye** [comment]
Hello all,
We have updated the demo store template with new Remix based Hydrogen v2. It takes a bit time since we were working on our FE libraries for Remix compatibility. The implementation steps are available in readme.
Thanks,
Best regards
